system_prompt: |
  Think step by step, but only keep minimum draft for each thinking step, with 5 words at most.
  Return the answer at the end of the response after a separator ####.
format: |
  Q: {question}
  A: {answer}
fewshot: [] 